=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'date'

module stcloud
  class ServiceIntegration
    attr_accessor :app_type_id

    attr_accessor :app_type_name

    attr_accessor :display_name

    attr_accessor :enabled

    attr_accessor :external_product_id

    attr_accessor :external_product_name

    attr_accessor :id

    attr_accessor :integration_type

    attr_accessor :ordinal

    attr_accessor :parent_integration_id

    attr_accessor :sematext_service

    attr_accessor :visible

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'app_type_id' => :'appTypeId',
        :'app_type_name' => :'appTypeName',
        :'display_name' => :'displayName',
        :'enabled' => :'enabled',
        :'external_product_id' => :'externalProductId',
        :'external_product_name' => :'externalProductName',
        :'id' => :'id',
        :'integration_type' => :'integrationType',
        :'ordinal' => :'ordinal',
        :'parent_integration_id' => :'parentIntegrationId',
        :'sematext_service' => :'sematextService',
        :'visible' => :'visible'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'app_type_id' => :'Object',
        :'app_type_name' => :'Object',
        :'display_name' => :'Object',
        :'enabled' => :'Object',
        :'external_product_id' => :'Object',
        :'external_product_name' => :'Object',
        :'id' => :'Object',
        :'integration_type' => :'Object',
        :'ordinal' => :'Object',
        :'parent_integration_id' => :'Object',
        :'sematext_service' => :'Object',
        :'visible' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `stcloud::ServiceIntegration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `stcloud::ServiceIntegration`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'app_type_id')
        self.app_type_id = attributes[:'app_type_id']
      end

      if attributes.key?(:'app_type_name')
        self.app_type_name = attributes[:'app_type_name']
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      end

      if attributes.key?(:'external_product_id')
        self.external_product_id = attributes[:'external_product_id']
      end

      if attributes.key?(:'external_product_name')
        self.external_product_name = attributes[:'external_product_name']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'integration_type')
        self.integration_type = attributes[:'integration_type']
      end

      if attributes.key?(:'ordinal')
        self.ordinal = attributes[:'ordinal']
      end

      if attributes.key?(:'parent_integration_id')
        self.parent_integration_id = attributes[:'parent_integration_id']
      end

      if attributes.key?(:'sematext_service')
        self.sematext_service = attributes[:'sematext_service']
      end

      if attributes.key?(:'visible')
        self.visible = attributes[:'visible']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          app_type_id == o.app_type_id &&
          app_type_name == o.app_type_name &&
          display_name == o.display_name &&
          enabled == o.enabled &&
          external_product_id == o.external_product_id &&
          external_product_name == o.external_product_name &&
          id == o.id &&
          integration_type == o.integration_type &&
          ordinal == o.ordinal &&
          parent_integration_id == o.parent_integration_id &&
          sematext_service == o.sematext_service &&
          visible == o.visible
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [app_type_id, app_type_name, display_name, enabled, external_product_id, external_product_name, id, integration_type, ordinal, parent_integration_id, sematext_service, visible].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        stcloud.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
