=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for stcloud::BillingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @instance = stcloud::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@instance).to be_instance_of(stcloud::BillingApi)
    end
  end

  # unit tests for get_detailed_invoice_using_get
  # Get invoice details
  # @param service service
  # @param year year
  # @param month month
  # @param [Hash] opts the optional parameters
  # @return [GenericApiResponse]
  describe 'get_detailed_invoice_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_available_plans_using_get
  # Get available plans
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :integration_id integrationId
  # @option opts [String] :app_type appType
  # @return [GenericApiResponse]
  describe 'list_available_plans_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_plan_using_put
  # Update plan for an app
  # @param app_id appId
  # @param dto dto
  # @param [Hash] opts the optional parameters
  # @return [GenericApiResponse]
  describe 'update_plan_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
