=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for stcloud::LogsAppApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LogsAppApi' do
  before do
    # run before each test
    @instance = stcloud::LogsAppApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogsAppApi' do
    it 'should create an instance of LogsAppApi' do
      expect(@instance).to be_instance_of(stcloud::LogsAppApi)
    end
  end

  # unit tests for create_logsene_application
  # Create Logs App
  # @param body Details of the application to be created
  # @param [Hash] opts the optional parameters
  # @return [AppsResponse]
  describe 'create_logsene_application test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
