=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'

# Unit tests for SematextCloud::ResetPasswordApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResetPasswordApi' do
  before do
    # run before each test
    @instance = SematextCloud::ResetPasswordApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResetPasswordApi' do
    it 'should create an instance of ResetPasswordApi' do
      expect(@instance).to be_instance_of(SematextCloud::ResetPasswordApi)
    end
  end

  # unit tests for reset_password_using_post
  # Reset Password
  # @param body dto
  # @param [Hash] opts the optional parameters
  # @return [GenericMapBasedApiResponse]
  describe 'reset_password_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
