=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for stcloud::SavedQueriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SavedQueriesApi' do
  before do
    # run before each test
    @instance = stcloud::SavedQueriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SavedQueriesApi' do
    it 'should create an instance of SavedQueriesApi' do
      expect(@instance).to be_instance_of(stcloud::SavedQueriesApi)
    end
  end

  # unit tests for delete_saved_query_using_delete
  # Delete saved query
  # @param updateable_query_id updateableQueryId
  # @param [Hash] opts the optional parameters
  # @return [GenericApiResponse]
  describe 'delete_saved_query_using_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_saved_queries_for_app_using_get
  # Get saved queries for an app
  # @param app_id appId
  # @param [Hash] opts the optional parameters
  # @return [GenericApiResponse]
  describe 'get_saved_queries_for_app_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for save_query_using_post
  # Create saved query
  # @param saved_query_dto savedQueryDto
  # @param [Hash] opts the optional parameters
  # @return [GenericApiResponse]
  describe 'save_query_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for save_query_using_put
  # Update saved query
  # @param saved_query_dto savedQueryDto
  # @param updateable_query_id updateableQueryId
  # @param [Hash] opts the optional parameters
  # @return [GenericApiResponse]
  describe 'save_query_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
