=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.25
=end

require 'spec_helper'
require 'json'

# Unit tests for stcloud::TokensApiControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TokensApiControllerApi' do
  before do
    # run before each test
    @instance = stcloud::TokensApiControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TokensApiControllerApi' do
    it 'should create an instance of TokensApiControllerApi' do
      expect(@instance).to be_instance_of(stcloud::TokensApiControllerApi)
    end
  end

  # unit tests for create_app_token1
  # Create new app token
  # @param body dto
  # @param app_id appId
  # @param [Hash] opts the optional parameters
  # @return [TokenResponse]
  describe 'create_app_token1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_app_token
  # Delete app token
  # @param app_id appId
  # @param token_id tokenId
  # @param [Hash] opts the optional parameters
  # @return [GenericMapBasedApiResponse]
  describe 'delete_app_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_app_tokens1
  # Get app available tokens
  # @param app_id appId
  # @param [Hash] opts the optional parameters
  # @return [TokensResponse]
  describe 'get_app_tokens1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for regenerate_app_token
  # Regenerate app token)
  # @param app_id appId
  # @param token_id tokenId
  # @param [Hash] opts the optional parameters
  # @return [TokenResponse]
  describe 'regenerate_app_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_app_token
  # Update app token (enable/disable or name)
  # @param body dto
  # @param app_id appId
  # @param token_id tokenId
  # @param [Hash] opts the optional parameters
  # @return [TokenResponse]
  describe 'update_app_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
