=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'date'

module SematextCloud
  class Plan
    attr_accessor :app_type

    attr_accessor :custom

    attr_accessor :data_retention_hours

    attr_accessor :default_trial_plan

    attr_accessor :free

    attr_accessor :free_trial_days

    attr_accessor :id

    attr_accessor :max_alerts

    attr_accessor :max_daily_events

    attr_accessor :name

    attr_accessor :plan_scheme

    attr_accessor :sematext_service

    attr_accessor :trial_plan

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'app_type' => :'appType',
        :'custom' => :'custom',
        :'data_retention_hours' => :'dataRetentionHours',
        :'default_trial_plan' => :'defaultTrialPlan',
        :'free' => :'free',
        :'free_trial_days' => :'freeTrialDays',
        :'id' => :'id',
        :'max_alerts' => :'maxAlerts',
        :'max_daily_events' => :'maxDailyEvents',
        :'name' => :'name',
        :'plan_scheme' => :'planScheme',
        :'sematext_service' => :'sematextService',
        :'trial_plan' => :'trialPlan'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'app_type' => :'Object',
        :'custom' => :'Object',
        :'data_retention_hours' => :'Object',
        :'default_trial_plan' => :'Object',
        :'free' => :'Object',
        :'free_trial_days' => :'Object',
        :'id' => :'Object',
        :'max_alerts' => :'Object',
        :'max_daily_events' => :'Object',
        :'name' => :'Object',
        :'plan_scheme' => :'Object',
        :'sematext_service' => :'Object',
        :'trial_plan' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SematextCloud::Plan` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SematextCloud::Plan`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'app_type')
        self.app_type = attributes[:'app_type']
      end

      if attributes.key?(:'custom')
        self.custom = attributes[:'custom']
      end

      if attributes.key?(:'data_retention_hours')
        self.data_retention_hours = attributes[:'data_retention_hours']
      end

      if attributes.key?(:'default_trial_plan')
        self.default_trial_plan = attributes[:'default_trial_plan']
      end

      if attributes.key?(:'free')
        self.free = attributes[:'free']
      end

      if attributes.key?(:'free_trial_days')
        self.free_trial_days = attributes[:'free_trial_days']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'max_alerts')
        self.max_alerts = attributes[:'max_alerts']
      end

      if attributes.key?(:'max_daily_events')
        self.max_daily_events = attributes[:'max_daily_events']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'plan_scheme')
        self.plan_scheme = attributes[:'plan_scheme']
      end

      if attributes.key?(:'sematext_service')
        self.sematext_service = attributes[:'sematext_service']
      end

      if attributes.key?(:'trial_plan')
        self.trial_plan = attributes[:'trial_plan']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      plan_scheme_validator = EnumAttributeValidator.new('Object', ['SPM_1_0', 'SPM_2_0', 'SEARCHENE_1_0', 'LOGSENE_1_0', 'LOGSENE_2_0', 'RUM_1_0', 'RUM_1_1', 'RUM_EA', 'SYNTHETICS_EA', 'SYNTHETICS_1_0', 'BUGZ_EA'])
      return false unless plan_scheme_validator.valid?(@plan_scheme)
      sematext_service_validator = EnumAttributeValidator.new('Object', ['LOGSENE', 'SPM', 'RUM', 'SYNTHETICS'])
      return false unless sematext_service_validator.valid?(@sematext_service)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] plan_scheme Object to be assigned
    def plan_scheme=(plan_scheme)
      validator = EnumAttributeValidator.new('Object', ['SPM_1_0', 'SPM_2_0', 'SEARCHENE_1_0', 'LOGSENE_1_0', 'LOGSENE_2_0', 'RUM_1_0', 'RUM_1_1', 'RUM_EA', 'SYNTHETICS_EA', 'SYNTHETICS_1_0', 'BUGZ_EA'])
      unless validator.valid?(plan_scheme)
        fail ArgumentError, "invalid value for \"plan_scheme\", must be one of #{validator.allowable_values}."
      end
      @plan_scheme = plan_scheme
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sematext_service Object to be assigned
    def sematext_service=(sematext_service)
      validator = EnumAttributeValidator.new('Object', ['LOGSENE', 'SPM', 'RUM', 'SYNTHETICS'])
      unless validator.valid?(sematext_service)
        fail ArgumentError, "invalid value for \"sematext_service\", must be one of #{validator.allowable_values}."
      end
      @sematext_service = sematext_service
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          app_type == o.app_type &&
          custom == o.custom &&
          data_retention_hours == o.data_retention_hours &&
          default_trial_plan == o.default_trial_plan &&
          free == o.free &&
          free_trial_days == o.free_trial_days &&
          id == o.id &&
          max_alerts == o.max_alerts &&
          max_daily_events == o.max_daily_events &&
          name == o.name &&
          plan_scheme == o.plan_scheme &&
          sematext_service == o.sematext_service &&
          trial_plan == o.trial_plan
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [app_type, custom, data_retention_hours, default_trial_plan, free, free_trial_days, id, max_alerts, max_daily_events, name, plan_scheme, sematext_service, trial_plan].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        SematextCloud.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
