=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

# Common files
require 'SematextCloud/api_client'
require 'SematextCloud/api_error'
require 'SematextCloud/version'
require 'SematextCloud/configuration'

# Models
require 'SematextCloud/models/alert_notification'
require 'SematextCloud/models/alert_notification_request'
require 'SematextCloud/models/alert_rule'
require 'SematextCloud/models/alert_rule_response'
require 'SematextCloud/models/alert_rule_response_entry'
require 'SematextCloud/models/alert_rule_schedule_time_range_dto'
require 'SematextCloud/models/alert_rule_schedule_weekday_dto'
require 'SematextCloud/models/alert_rules_response'
require 'SematextCloud/models/alert_rules_response_entry'
require 'SematextCloud/models/app'
require 'SematextCloud/models/app_description'
require 'SematextCloud/models/app_metadata'
require 'SematextCloud/models/app_response'
require 'SematextCloud/models/app_response_entry'
require 'SematextCloud/models/app_types_response'
require 'SematextCloud/models/app_types_response_entry'
require 'SematextCloud/models/apps_response'
require 'SematextCloud/models/apps_response_entry'
require 'SematextCloud/models/basic_auth_method_dto'
require 'SematextCloud/models/basic_organization_dto'
require 'SematextCloud/models/billing_info'
require 'SematextCloud/models/charges_details_response_dto'
require 'SematextCloud/models/cloud_watch_settings'
require 'SematextCloud/models/cloud_watch_settings_response'
require 'SematextCloud/models/cloud_watch_settings_response_entry'
require 'SematextCloud/models/create_app_info'
require 'SematextCloud/models/create_token_dto'
require 'SematextCloud/models/daily_dto'
require 'SematextCloud/models/day_usage_data'
require 'SematextCloud/models/dimension'
require 'SematextCloud/models/error'
require 'SematextCloud/models/event_dto'
require 'SematextCloud/models/filter_value'
require 'SematextCloud/models/generic_api_response'
require 'SematextCloud/models/generic_map_based_api_response'
require 'SematextCloud/models/invitation'
require 'SematextCloud/models/invoice'
require 'SematextCloud/models/invoice_response'
require 'SematextCloud/models/invoice_response_entry'
require 'SematextCloud/models/limit_change_event_dto'
require 'SematextCloud/models/mail_report_response'
require 'SematextCloud/models/mail_report_response_response_entry'
require 'SematextCloud/models/min_period_fee_period'
require 'SematextCloud/models/notification_integration'
require 'SematextCloud/models/notifications_response'
require 'SematextCloud/models/notifications_response_entry'
require 'SematextCloud/models/plan'
require 'SematextCloud/models/plans_response'
require 'SematextCloud/models/plans_response_entry'
require 'SematextCloud/models/report_info'
require 'SematextCloud/models/service_integration'
require 'SematextCloud/models/subscription'
require 'SematextCloud/models/subscription_dashboard_dto'
require 'SematextCloud/models/subscription_dto'
require 'SematextCloud/models/subscription_response'
require 'SematextCloud/models/subscription_response_entry'
require 'SematextCloud/models/subscriptions_response'
require 'SematextCloud/models/subscriptions_response_entry'
require 'SematextCloud/models/tag_names_response'
require 'SematextCloud/models/token_dto'
require 'SematextCloud/models/token_response'
require 'SematextCloud/models/token_response_entry'
require 'SematextCloud/models/tokens_response'
require 'SematextCloud/models/tokens_response_entry'
require 'SematextCloud/models/update_app_info'
require 'SematextCloud/models/update_plan_response'
require 'SematextCloud/models/update_plan_response_dto'
require 'SematextCloud/models/update_plan_response_entry'
require 'SematextCloud/models/update_subscription_dto'
require 'SematextCloud/models/update_token_dto'
require 'SematextCloud/models/usage_dto'
require 'SematextCloud/models/usage_multi_response'
require 'SematextCloud/models/usage_multi_response_entry'
require 'SematextCloud/models/usage_response'
require 'SematextCloud/models/usage_response_entry'
require 'SematextCloud/models/user_info'
require 'SematextCloud/models/user_permissions'
require 'SematextCloud/models/user_role'

# APIs
require 'SematextCloud/api/alert_notifications_api'
require 'SematextCloud/api/alerts_api'
require 'SematextCloud/api/apps_api'
require 'SematextCloud/api/aws_settings_controller_api'
require 'SematextCloud/api/billing_api'
require 'SematextCloud/api/logs_app_api'
require 'SematextCloud/api/logs_usage_api_controller_api'
require 'SematextCloud/api/monitoring_app_api'
require 'SematextCloud/api/reset_password_api'
require 'SematextCloud/api/subscriptions_api'
require 'SematextCloud/api/tag_api_controller_api'
require 'SematextCloud/api/tokens_api_controller_api'

module SematextCloud
  class << self
    # Customize default settings for the SDK using block.
    #   SematextCloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
