=begin
#Sematext Cloud API

#API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

# Common files
require 'stcloud/api_client'
require 'stcloud/api_error'
require 'stcloud/version'
require 'stcloud/configuration'

# Models
require 'stcloud/models/alert_notification_request'
require 'stcloud/models/alert_rule'
require 'stcloud/models/alert_rule_schedule_time_range_dto'
require 'stcloud/models/alert_rule_schedule_weekday_dto'
require 'stcloud/models/app'
require 'stcloud/models/app_description'
require 'stcloud/models/app_metadata'
require 'stcloud/models/basic_auth_method_dto'
require 'stcloud/models/basic_organization_dto'
require 'stcloud/models/billing_info'
require 'stcloud/models/cloud_watch_settings'
require 'stcloud/models/create_app_info'
require 'stcloud/models/data_series_filter'
require 'stcloud/models/data_series_request'
require 'stcloud/models/error'
require 'stcloud/models/filter_value'
require 'stcloud/models/generic_api_response'
require 'stcloud/models/invitation'
require 'stcloud/models/notification_integration'
require 'stcloud/models/plan'
require 'stcloud/models/report_info'
require 'stcloud/models/saved_query'
require 'stcloud/models/service_integration'
require 'stcloud/models/update_app_info'
require 'stcloud/models/user_info'
require 'stcloud/models/user_permissions'
require 'stcloud/models/user_role'

# APIs
require 'stcloud/api/alert_notifications_api'
require 'stcloud/api/alerts_api'
require 'stcloud/api/apps_api'
require 'stcloud/api/aws_settings_controller_api'
require 'stcloud/api/billing_api'
require 'stcloud/api/logs_app_api'
require 'stcloud/api/metrics_api'
require 'stcloud/api/monitoring_app_api'
require 'stcloud/api/reset_password_api'
require 'stcloud/api/saved_queries_api'
require 'stcloud/api/subscriptions_api'
require 'stcloud/api/tag_api_controller_api'

module stcloud
  class << self
    # Customize default settings for the SDK using block.
    #   stcloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
