name: Ruby Gem

on:
  release:
    types: [created]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Publish to RubyGems
      run: |       
        gem build *.gemspec
        gem push *.gem -k ${{secrets.RUBYGEMS_AUTH_TOKEN}}
